---
title: "Binomial Outcome"
author: "Thevaa Chandereng, Donald Musgrove, Tarek Haddad, Graeme Hickey, Timothy Hanson, Theodore Lystig"
output: 
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{bayesCT:binomial}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
  \usepackage[utf8]{inputenc}
---


```{r setup, echo=FALSE, results="hide"}
knitr::opts_chunk$set(comment = "#>", collapse = TRUE)
set.seed(28999)
```

```{r}
library(bayesCT)
```




# Binomial

```{r}

value <-
  binomial_outcome(p_treatment = 0.08) %>%
  historical_binomial(y0_treatment = 5, N0_treatment = 55,
                      discount_function = "identity", 
                      y0_control = NULL, N0_control = NULL, 
                      alpha_max = 1, fix_alpha = FALSE, 
                       weibull_scale = 0.135, weibull_shape = 3) %>%
  beta_prior(prior = c(1, 1)) %>%
  randomize(block_size = c(4, 6), randomization_ratio = c(1, 1)) %>%
  enrollment_rate(lambda = c(0.3, 1), time = 25) %>%
  study_details(total_sample_size = 900, study_period = 50,
                interim_look = c(410, 440, 670),
                prop_loss_to_followup = 0.10) %>%
  impute(no_of_impute = 25, number_mcmc = 1000) %>%
  hypothesis(delta = -0.03, futility_prob = 0.05, prob_ha = 0.95, 
             expected_success_prob = 0.90, alternative = "less") %>%
  BACTbinomial(no_of_sim = 5)


str(value)

```



```{r}
data(binomialdata)

value1 <-
  data_binomial(data = binomialdata) %>%
  historical_binomial(y0_treatment = 5, N0_treatment = 55,
                      y0_control = NULL, N0_control = NULL,
                      discount_function = "identity", 
                      alpha_max = 1, fix_alpha = FALSE, 
                      weibull_scale = 0.135, weibull_shape = 3) %>%
  beta_prior(prior = c(1, 1)) %>%
  impute(no_of_impute = 100, number_mcmc = 10000) %>%
  hypothesis(delta = 0.02, futility_prob = 0.05, prob_ha = 0.95, 
             expected_success_prob = 0.90, alternative = "greater") %>%
  BACTbinomial_analysis()


str(value1)

```

