---
title: "Time-to-Event Outcome"
author: "Thevaa Chandereng, Donald Musgrove, Tarek Haddad, Graeme Hickey, Timothy Hanson, Theodore Lystig"
header-includes:
   - \usepackage{amsmath}
output: 
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{bayesCT:binomial}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
  \usepackage[utf8]{inputenc}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Piecewise exponential function for time-to-event data

For time-to-event data, the piecewise constant hazard function for k different constant hazards is

$\begin{eqnarray}
	h(t) &=& \begin{cases}
	\lambda_1 & 0\leq t<\tau_1\\
	\lambda_2 & \tau_1\leq t <\tau_2\\
	\vdots & \vdots \\
	\lambda_{k} & t\geq\tau_{k - 1}
	\end{cases}
	\end{eqnarray}$.
	
We know that survival function $S(t)$, cumulative distribution function $F(t)$ and cumulative hazard function $H(t)$ are related.
$S(t) = \exp(-H(t))$, $exp(-H(t)) = 1 - F(t)$. 
If $U \sim Unif(0,1)$, then $F(X) = U$ is equivalent to $1-\exp(-H(X)) = U$, so $X=H^{-1}(-\log(1-U))$.  Note that $-\log(1-U) \sim Exp(1)$.
Thus, we can simulate $x$ in exponential distribution and substitute it into the inverse hazard function. 


$\begin{eqnarray}
H^{-1}(t)&=&\begin{cases}
\frac{t}{\lambda_1} & 0\leq t < \lambda_1\tau_1\\
\frac{t - \lambda_1\tau_1}{\lambda_2}+\tau_1 & \lambda_1\tau_1 \leq t < \lambda_1\tau_1 + \lambda_2(\tau_2-\tau_1)\\
	\vdots & \vdots \\
\frac{t - (\lambda_1\tau_1 + \sum_{i = 2}^{k - 2} \lambda_i (\tau_k - \tau_{k - 1}))}{\lambda_{k - 1}}+\tau_{k - 2} &  \lambda_1\tau_1 + \sum_{i = 2}^{k - 2} \lambda_i (\tau_k - \tau_{k - 1}) \leq t < \lambda_1\tau_1 + \sum_{i = 2}^{k - 1} \lambda_i (\tau_k - \tau_{k - 1})\\
\frac{t - (\lambda_1\tau_1 + \sum_{i = 2}^{k - 1} \lambda_i (\tau_k - \tau_{k - 1}))}{\lambda_k}+\tau_{k - 1} &  t \geq \lambda_1\tau_1 + \sum_{i = 2}^{k - 1} \lambda_i (\tau_k - \tau_{k - 1})\\
\end{cases}
\end{eqnarray}$

The `pw_exp_sim` function simulates time-to-event outcomes using piecewise constant hazard function. 



# Estimation of Treatment Difference 

Let $d_{ij}$ and $t_{ij}$ denote the the event indicator and event time or censoring time for the $i$th subject in the $j$th interval of the current data, respectively. Let $a_0$ and $b_0$ denote the shape and rate parameters of a gamma distribution, respectively. Then, the posterior distributions of the $j$th piecewise hazard rates for current and historical data, under vague (flat) priors are
$$\lambda_{j} \sim \mathcal{G}amma\left(a_0+D_j,\,b_0+T_j\right),$$
where $D_j=\sum_id_{ij}$, $T_j=\sum_it_{ij}$.
When historical data is present, let $d_{0ij}$ and $t_{0ij}$ denote the the event indicator and event time or censoring time for the $i$th subject in the $j$th interval of the historical data, respectively.
The weight of the historical data included in the study design and analysis is denoted by $\hat\alpha$. The computation of $\alpha$ is done using the discount prior approach \cite{haddad2017incorporation}.
The posterior distribution of the piecewise hazard rate for the historical data is
$$\lambda_{j} \sim \mathcal{G}amma\left(a_0+D_j + \alpha D_{0j},\,b_0+T_j + \alpha T_{0j}\right),$$
where $D_j=\sum_id_{ij}$, $T_j=\sum_it_{ij}$, $D_{0j}=\sum_id_{0ij}$, and $T_{j0}=\sum_it_{0ij}$.
Even though there is a closed-form solution for the difference in gamma distributed random variables, we use Monte Carlo simulations to estimate the treatment difference. 
The estimation of posterior chain of log-hazard rate comparing treatment and control groups is $\tilde{\lambda_{jT}} - \tilde{\lambda_{jT}}$, where $\lambda_{jT}$ is the posterior chain of log-hazard in the treatment group and $\lambda_C$ is the posterior chain of log-hazard in the control group.


# Wrapper Function for Design and Analysis

Unlike traditional R functions, the `bayesCT` package depends on pipe inputs with different wrapper functions. All the wrapper functions are illustrated below along with details on the arguments for the simulation and analysis.  

* **piecewise_exponential** - wrapper function for specifying observations. Inputs: 
    + **lambda_treatment** - hazard rate of the treatment group. Required input.
    + **cutoff_treatment** - timepoint cutoff for hazard rate of the treatment group. Required input if * lambda_treatment* is a vector of length two or more.This is the same for the control arm.  
    + **lambda_control** - hazard rate of the control group. Default value is NULL.
    

* **study_details** - wrapper function for specifying sample size, study length, interim looks, and loss to follow-up. Inputs:
    + **total_sample_size** - sample size required to run the simulation 
    + **study_period** - length of the study, i.e., the follow-up period
    + **interim_look** - enrollment values where interim looks are carried out. Specify where the trials are stopped to check for early success or futility. For more details on the early stopping for futility or success, please see [https://thevaachandereng.github.io/bayesCT/articles/bayesCT.html#early-stopping-for-futility-or-success](https://thevaachandereng.github.io/bayesCT/articles/bayesCT.html#early-stopping-for-futility-or-success). Each `interim_look` value must be smaller than `total_sample_size`. 
    + **prop_loss_to_followup** - proportion of subjects loss to follow-up. Must be a value be 0 and 1. Default value is 0.10. 


* **enrollment_rate** - wrapper function for specifying enrollment. Inputs: 
    + **lambda** - enrollment rate(s) at each `time`. Specified as patients per day. Can be a scalar or vector. Default is 0.3, i.e. 0.3 patients per day. 
    + **time** - determines the cut-off for the enrollment rates. Can be NULL, a scalar, or a vector. Default is NULL. For more details, please see  [https://thevaachandereng.github.io/bayesCT/articles/bayesCT.html#recruitment](https://thevaachandereng.github.io/bayesCT/articles/bayesCT.html#recruitment).  


* **hypothesis** - wrapper function for both simulation and analysis. Inputs:
    + **delta** - threshold difference between treatment and control groups or the threshold for single-arm trial (the default is set to 0). For non-inferiority trials, the difference must be < 0.  
    + **prob_accept_ha** - probability of accepting alternative hypothesis. Default value is 0.95. 
    + **futility_prob** - futility rate, i.e., $\omega$ in  [https://thevaachandereng.github.io/bayesCT/articles/bayesCT.html#futility](https://thevaachandereng.github.io/bayesCT/articles/bayesCT.html#futility). The default is set to 0.10. To prevent the trial for stopping for futility, set the **futility_prob** to 0. 
    + **expected_success_prob** - controls stopping early for success rate, i.e., $\Delta$ in https://thevaachandereng.github.io/bayesCT/articles/bayesCT.html#success](https://thevaachandereng.github.io/bayesCT/articles/bayesCT.html#success). The default value is 0.90. To prevent the trial for stopping for early success, use 1.
    + **alternative** - sign of the alternative hypothesis. Character string specifying one of "greater" $\lambda_{treatment} > \lambda_{control}$ (default), "less" $\lambda_{treatment} < \lambda_{control}$ or "two-sided" $\lambda_{treatment} \neq \lambda_{control}$.


* **randomize** - wrapper function for specifying the randomization scheme. Inputs: 
    + **block_size** - size of each enrollment block. 
    + **randomization_ratio** - ratio of control to treatment, specified as a vector of length 2. For more details, see [https://thevaachandereng.github.io/bayesCT/articles/bayesCT.html#randomization-scheme](https://thevaachandereng.github.io/bayesCT/articles/bayesCT.html#randomization-scheme).  


* **impute** - wrapper function specifying imputation of outcomes at the interim looks. Inputs:
    + **no_of_impute** - number of imputations. Used to impute outcomes for subjects potentially loss to follow-up when estimating the probability of stopping for early success and/or futility. In the case of the futility calculation, subjects not yet enrolled or imputed as well. Default value is 10 so that the vignette can be generated quickly. However, much larger values should be used in practice, e.g., 10000.
    + **number_mcmc** - number of Monte Carlo iterations for sampling from posterior distributions during imputation. Default value is 10000.  

* **historical_survival** - wrapper function for specifying historical data, if available. This function should only be used when historical data is incorporated in the analysis or simulation. For more details on the method and computation, please see [https://CRAN.R-project.org/package=bayesDP](https://CRAN.R-project.org/package=bayesDP). Inputs:
    + **time_treatment** - This is the follow up time for treatment group, it could be right-censored.
    + **status_treatment** - The status indicator for treatment group, normally 0=alive, 1=dead.
    + **time_control** - This is the follow up time for control group, it could be right-censored.
    + **status_control** - The status indicator for control group, normally 0=alive, 1=dead.
    + **discount_function** - discount function to use for controlling the weight given to the historical data. Currently supports `weibull`, `scaledweibull`, and `identity`. The discount function `scaledweibull` scales the output of the Weibull CDF to have a max value of 1. The `identity` discount function uses the posterior probability directly as the discount weight. Default value is `"identity"`.
    + **alpha_max** - maximum weight the discount function can apply. Default is 1. For a two-arm trial, users may specify a vector of two values where the first value is used to weight the historical treatment group and the second value is used to weight the historical control group.
    + **fix_alpha** - Should alpha be set to alpha_max? Default value is FALSE.
    + **weibull_scale** - scale parameter of the Weibull discount function used to compute alpha, the weight parameter of the historical data. Default value is 0.135. For a two-arm trial, users may specify a vector of two values where the first value is used to estimate the weight of the historical treatment group and the second value is used to estimate the weight of the historical control group. Not used when `discount_function = "identity"`.
    + **weibull_shape** - shape parameter of the Weibull discount function used to compute alpha, the weight parameter of the historical data. Default value is 3. For a two-arm trial, users may specify a vector of two values where the first value is used to estimate the weight of the historical treatment group and the second value is used to estimate the weight of the historical control group. Not used when `discount_function = "identity"`.

* **analysis** - wrapper function for analyzing a trial. Inputs:
    + **input** - list of input to analyze the adaptive trial. 
    + **type** - outcome type of the trial. Use `type="survival"` for a trial with normal outcomes. 


* **simulate** - wrapper function for simulating trials. Should be used as the terminal end of the pipe. Inputs: 
    + **input** - list of inputs specifying the adaptive trial simulation set-up.
    + **no_of_sim** - number of trials to simulate. Default value is 10000. 


# Design of Adaptive Trials

In the following section, we will discuss the design of adaptive trials using `bayesCT` for time-to-events outcomes. We illustrate an example for one-arm trial and two-arm trials using the wrapper functions described above. 


## One-arm Trial

In the example below, we will illustrate how to compute power, type 1 error, and other clinical trial characteristics for an objective performace criterion (OPC) trial with mean outcome and hypothesis described as follows, 
$$H_0: p_{treatment} \geq 0.10  \qquad H_A:p_{treatment} < 0.10$$

The most important wrapper functions are **study_details** and **normal_outcome** (especially since there are no default values).

The normal mean outcomes are simulated using a mean value of 120 and standard deviation of 5.5. The total sample size is 400 with a study length of 60 days. A 10% loss to follow up is assumed. Based on this information, the adaptive trials are simulated 10 times to obtain the following output (**NOTE**:  for the purpose of reproducing the vignette quickly, we reduce the number of simulations to 10, you should use a much larger value, e.g., 10000). The aforementioned inputs were chosen for illustration purposes only.

